export default {
    googleIcon: require('../assets/Images/socialIcons/googleIcon.png'),
    facebookIcon: require('../assets/Images/socialIcons/facebookIcon.png'),
    checkMarkIcon: require('../assets/Images/icons/checkmark.jpg'),
    OnboardingImg: require('../assets/Images/onBoarding/onboardingImg.jpg'),
    dress: require('../assets/Images/categories/dress.png'),
    gamingPad: require('../assets/Images/categories/gamingPad.png'),
    lipstick: require('../assets/Images/categories/lipstick.png'),
    stationery: require('../assets/Images/categories/stationery.png'),
    gym: require('../assets/Images/categories/gym.png'),
    sofa: require('../assets/Images/categories/sofa.png'),
    carousel1: require('../assets/Images/carousel/carousel1.png'),
    star: require('../assets/Images/icons/star.png'),
    searchImg: require('../assets/Images/notFound/searchImg.png'),
    reviewStar: require('../assets/Images/icons/reviewStar.png'),
    emptyStar: require('../assets/Images/icons/emptyStar.png'),
    trashIcon: require('../assets/Images/icons/trashIcon.png'),
    checkmarkCircle: require('../assets/Images/icons/checkmarkCircle.png'),
    visaIcon: require('../assets/Images/icons/visaIcon.png'),
}